version: "3"
services:
  db:
    build: ./mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
  bot:
    build: ./BOT
    ports:
      - "9999:9999"
    links:
      - api
      - client
  api:
    build: ./API
    ports:
      - "3030:3030"
    links:
      - db
  client:
    build: ./CLIENT
    ports:
      - "80:80"
    links:
      - api